config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path, notice: "「#{@task.name}」を追加しました。"
    else
      flash.now[:alert] = "タスクの作成が失敗しました。もう一度やり直してください。"
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to root_path, notice: "「#{@task.name}」を更新しました。"
    else
      flash.now[:alert] = "タスクの更新が失敗しました。もう一度やり直してください。"
      render :edit
    end
  end

  def destroy
    @task.destroy!
    redirect_to root_path, notice: "「#{@task.name}」を削除しました。"
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.slim
= form_with(model: task, local: true) do |f|
  = f.label :name
  = f.text_field :name

  = f.label :description
  = f.text_field :description

  = f.submit

= link_to "TOPへ戻る", root_path

app/views/tasks/edit.html.slim
h1 タスク編集画面

= render partial: "form", locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧画面

table
  thead
    tr
      th name
      th description
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.name, task
        td= simple_format(task.description)
        td= link_to "編集", edit_task_path(task)
        td= link_to "削除", task_path(task), method: :delete, data: { confirm: "「#{task.name}」を削除してもよろしいですか？" }

= link_to "新しいタスクを登録する", new_task_path
= link_to "ユーザー一覧", users_path

app/views/tasks/new.html.slim
h1 タスク作成画面

= render partial: "form", locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスク詳細画面

= @task.name
= simple_format(@task.description)

= link_to "TOPへ戻る", root_path

app/views/users/index.html.slim
h1 タスク一覧画面

table
  thead
    tr
      th name
      th email
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= user.email